=== roypeer/RapidJson-C-Wrapper/complex_schema_playground/complex_person_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Person",
    "definitions": {
        "Person": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "first_name": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 2
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "id": {
                    "type": "string",
                    "minLength": 7,
                    "maxLength": 30
                },
                "email": {
                    "type": "string",
                    "pattern": "^[a-zA-Z0-9]{1,40}@[a-zA-Z0-9]{1,30}.com$",
                    "minLength": 7,
                    "maxLength": 200
                },
                "age": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 99
                },
                "father_details": {
                    "$ref": "#/definitions/FatherDetails"
                },
                "mother_details": {
                    "$ref": "#/definitions/MotherDetails"
                },
                "city_of_residence": {
                    "type": "string",
                    "minLength": 2,
                    "maxLength": 100
                },
                "zip_code": {
                    "type": "string",
                    "format": "integer",
                    "minLength": 7,
                    "maxLength": 7
                },
                "does_have_pet": {
                    "type": "boolean"
                },
                "number_of_siblings": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 40
                },
                "favorite_book": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50
                },
                "favorite_color": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50
                },
                "hobbies": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "minLength": 2,
                        "maxLength": 50
                    },
                    "minItems": 0,
                    "maxItems": 30,
                    "uniqueItems": true
                },
                "nationality": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50
                },
                "religion": {
                    "type": "string",
                    "enum": ["Judaism", "Christianity", "Islam", "Buddhism"]
                },
                "favorite_singer": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50
                },
                "favorite_tv_show": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50
                },
                "country_of_birth": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 50
                },
                "likes_coffee": {
                    "type": "boolean"
                },
                "yanny_or_laurel": {
                    "type": "string",
                    "enum": ["yanny", "laurel"]
                },
                "is_vegan": {
                    "type": "boolean"
                },
                "phone_number_optional": {
                    "type": "string",
                    "pattern": "^05[248]{1}-[0-9]{7}$",
                    "minLength": 11,
                    "maxLength": 11
                }
            },
            "required": [
                "age",
                "city_of_residence",
                "country_of_birth",
                "does_have_pet",
                "email",
                "father_details",
                "favorite_book",
                "favorite_color",
                "favorite_singer",
                "favorite_tv_show",
                "first_name",
                "hobbies",
                "id",
                "is_vegan",
                "last_name",
                "likes_coffee",
                "mother_details",
                "nationality",
                "number_of_siblings",
                "religion",
                "yanny_or_laurel",
                "zip_code"
            ],
            "title": "Person"
        },
        "FatherDetails": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "first_name": {
                    "type": "string"
                }
            },
            "required": [
                "first_name"
            ],
            "title": "FatherDetails"
        },
        "MotherDetails": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "last_name": {
                    "type": "string"
                }
            },
            "required": [
                "last_name"
            ],
            "title": "MotherDetails"
        }
    }
}

=== roypeer/RapidJson-C-Wrapper/complex_schema_playground/people/roypeer - Copy - Copy - Copy - Copy (2).json
{
    "first_name": "Roy",
    "last_name": "Peter",
    "id": "123456789",
    "email": "royp@gmail.com",
    "age": 19,
    "father_details": {
        "first_name": "Yaron"
    },
    "mother_details": {
        "last_name": "Tamara"
    }, 
    "city_of_residence": "Tel-Aviv yafo",
    "zip_code": "6931234",
    "does_have_pet": false,
    "number_of_siblings": 2,
    "favorite_book": "The Wizard Of Oz",
    "favorite_color": "Pink",
    "hobbies": [
        "reading",
        "running",
        "programming"
    ],
    "nationality": "Israeli",
    "religion": "Judaism",
    "favorite_singer": "Elton John",
    "favorite_tv_show": "Fauda",
    "country_of_birth": "Zimbabwe",
    "likes_coffee": true,
    "yanny_or_laurel": "yanny",
    "is_vegan": false,
    "phone_number_optional": "054-1234567"
}

=== roypeer/RapidJson-C-Wrapper/complex_schema_playground/people/michaelamador - Copy (5).json
{
    "first_name": "Michael",
    "last_name": "Amador",
    "id": "123456789",
    "email": "mic@comp.com",
    "age": 34,
    "father_details": {
        "first_name": "Tim"
    },
    "mother_details": {
        "last_name": "Roxin"
    }, 
    "city_of_residence": "New york",
    "zip_code": "6931232",
    "does_have_pet": true,
    "number_of_siblings": 2,
    "favorite_book": "Moby Dick",
    "favorite_color": "Pink",
    "hobbies": [
        "running",
        "shooting stuff"
    ],
    "nationality": "American",
    "religion": "Islam",
    "favorite_singer": "Tim Robbins",
    "favorite_tv_show": "NCIS",
    "country_of_birth": "Turkey",
    "likes_coffee": true,
    "yanny_or_laurel": "yanny",
    "is_vegan": false,
    "phone_number_optional": "054-2234567"

}

=== roypeer/RapidJson-C-Wrapper/complex_schema_playground/people/Spiderman - Copy (2).json
{
    "first_name": "Spiderman",
    "last_name": "Robbins",
    "id": "987654321",
    "email": "spid@comp.com",
    "age": 18,
    "father_details": {
        "first_name": "eve"
    },
    "mother_details": {
        "last_name": "lin"
    }, 
    "city_of_residence": "New york",
    "zip_code": "4456781",
    "does_have_pet": true,
    "number_of_siblings": 2,
    "favorite_book": "Batman book",
    "favorite_color": "Red",
    "hobbies": [
        "running",
        "shooting stuff"
    ],
    "nationality": "American",
    "religion": "Christianity",
    "favorite_singer": "Tim Robbins",
    "favorite_tv_show": "NCIS",
    "country_of_birth": "Turkey",
    "likes_coffee": true,
    "yanny_or_laurel": "yanny",
    "is_vegan": false,
    "phone_number_optional": "054-3451267"

}

=== roypeer/RapidJson-C-Wrapper/complex_schema_playground/people/abrhaham - Copy (9) - Copy - Copy.json
{
    "first_name": "Abraham",
    "last_name": "Avino",
    "id": "987654321",
    "email": "abr@bible.com",
    "age": 97,
    "father_details": {
        "first_name": "Kayn"
    },
    "mother_details": {
        "last_name": "Hevel"
    }, 
    "city_of_residence": "Or Kasdim",
    "zip_code": "4567891",
    "does_have_pet": true,
    "number_of_siblings": 0,
    "favorite_book": "The bible",
    "favorite_color": "Pink",
    "hobbies": [
        "reading"
    ],
    "nationality": "Israeli",
    "religion": "Judaism",
    "favorite_singer": "Hava",
    "favorite_tv_show": "Rockstats",
    "country_of_birth": "Syria",
    "likes_coffee": true,
    "yanny_or_laurel": "yanny",
    "is_vegan": false
}
